#pragma once

#include "..\..\Core\Core.h"

typedef struct tagStaticMeshVertex
{
	Vector3 Position;
	Vector4 Color;
	Vector3 Normal;
	Vector2 TexCoord;
	Vector3 Tangent;
}STATICMESHVERTEX, *LPSTATICMESHVERTEX;


typedef struct tagSkinnedMeshVertex
{
	Vector3 Position;
	Vector4 Color;
	Vector3 Normal;
	Vector2 TexCoord;
	Vector3 Tangent;
	Vector3	Weight{ 0.0f, 0.0f, 0.0f };	// °¡ÁßÄ¡ °ª 4°³
	int		Index[4] = { 0, 0, 0, 0 };			// »À´ë ÀÎµ¦½º


}SKINNEDMESHVERTEX, *LPSKINNEDMESHVERTEX;


const D3DVERTEXELEMENT9 StaticMeshDec[6] =
{
	{ 0, 0,  D3DDECLTYPE_FLOAT3, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_POSITION, 0 },
	{ 0, 12, D3DDECLTYPE_FLOAT4, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_COLOR, 0 },
	{ 0, 28, D3DDECLTYPE_FLOAT3, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_NORMAL, 0 },
	{ 0, 40, D3DDECLTYPE_FLOAT2, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_TEXCOORD, 0 },
	{ 0, 48, D3DDECLTYPE_FLOAT3, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_TANGENT, 0 },
	D3DDECL_END()
};

const D3DVERTEXELEMENT9 SkinnedMeshDec[8] =
{
	{ 0, 0,  D3DDECLTYPE_FLOAT3, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_POSITION, 0 },
	{ 0, 12, D3DDECLTYPE_FLOAT4, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_COLOR, 0 },
	{ 0, 28, D3DDECLTYPE_FLOAT3, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_NORMAL, 0 },
	{ 0, 40, D3DDECLTYPE_FLOAT2, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_TEXCOORD, 0 },
	{ 0, 48, D3DDECLTYPE_FLOAT3, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_TANGENT, 0 },
	{ 0, 60, D3DDECLTYPE_FLOAT3, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_BLENDWEIGHT,0 },
	{ 0, 72, D3DDECLTYPE_UBYTE4, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_BLENDINDICES,0 },
	D3DDECL_END()
};
